query getAllUsers(
  $limit: Int!
  $offset: Int!
  $order_by: [users_order_by!]
  $where: users_bool_exp
) {
  users(limit: $limit, offset: $offset, order_by: $order_by, where: $where) {
    created_at
    email
    first_name
    id
    last_name
    profile_image_url
    updated_at
    role
    status
  }
  users_aggregate(where: $where) {
    aggregate {
      count
    }
  }
}
