query GetMyEvents(
  $user_id: uuid!
  $limit: Int
  $offset: Int
  $order_by: [events_order_by!]
) {
  events(
    where: { user_id: { _eq: $user_id } }
    limit: $limit
    offset: $offset
    order_by: $order_by
  ) {
    categories
    created_at
    description
    event_date
    event_end_time
    event_start_time
    featured_image_url
    id
    location
    preparation_time
    price
    quantity
    tags
    title
    total_ticket
    user_id
    venue
  }
}
